version: "3"
services:
  selenium-node-chrome:
    image: selenium/node-chrome
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443 
    depends_on:
      - selenium-hub
    ports:
      - "7900:5900"  # Expose VNC port for the browser window

  taylorshow:
    image: taylorshow:latest
    depends_on:
      - selenium-hub
      - selenium-node-chrome

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"