version: "3"
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  selenium-node-chrome:
    image: selenium/node-chrome
    ports:
      - "7900:5900"  # Expose VNC port for the browser window
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4444
      - SE_EVENT_BUS_SUBSCRIBE_PORT=5555 

  taylorshow:
    image: taylorshow:latest
    depends_on:
      - selenium-hub
      - selenium-node-chrome
